steps:
- id: "Run docker-compose"
  name: "docker/compose"
  args: ['-f', 'docker-compose.integration.yml', 'up', '-d']
- id: "Run chown"
  name: "docker"
  args: ['exec', '-u', 'root', '-t', 'micro-videos-catalog-app', 'chown', '-R', 'www-data:www-data', '.']
- id: "Copy .env"
  name: "docker"
  args: ['exec', '-t', 'micro-videos-catalog-app', 'cp', '.env.example', '.env']
- id: "Copy .env.testing"
  name: "docker"
  args: ['exec', '-t', 'micro-videos-catalog-app', 'cp', '.env.testing.example', '.env.testing']
- id: "Run Composer"
  name: "docker"
  args: ['exec', '-t', 'micro-videos-catalog-app', 'composer', 'install']
- id: "Run artisan key:generate"
  name: "docker"
  args: ['exec', '-t', 'micro-videos-catalog-app', 'php', 'artisan', 'key:generate']
- id: "Run migrations"
  name: "docker"
  args: ['exec', '-t', 'micro-videos-catalog-app', 'php', 'artisan', 'migrate']
- id: "Run tests"
  name: "docker"
  args: ['exec', '-t', 'micro-videos-catalog-app', 'php', './vendor/bin/phpunit', '-c', './phpunit.xml']
