version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: micro-videos-catalog-app
    entrypoint: dockerize -template ./.docker/app/.env.template:.env --wait tcp://db:3306 --timeout 2m ./.docker/app/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=videos-catalog
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: micro-videos-catalog-nginx
    restart: always
    tty: true
    ports:
        - "8000:80"
    volumes:
        - .:/var/www
    networks:
        - app-network
    depends_on:
        - app

  db:
    build: ./.docker/mysql
    container_name: micro-videos-catalog-db
    restart: always
    tty: true
    ports:
        - "33006:3306"
    volumes:
        - ./.docker/dbdata:/var/lib/mysql
    environment:
        - MYSQL_DATABASE=videos-catalog
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
    networks:
        - app-network


  redis:
    image: redis:alpine
    container_name: micro-videos-catalog-redis
    expose:
        - 6379
    networks:
        - app-network

networks:
    app-network:
        driver: bridge
